# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: samvbeckmann
email: samvbeckmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What happens when I write something here?
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /blog/:categories/:year/:month/:day/:title.html
url: https://samvbeckmann.com # the base hostname & protocol for your site
enforce_ssl: samvbeckmann.com
twitter_username: samvbeckmann
github_username:  samvbeckmann

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
